working in the deployment of worker to the k8s cluster

diff --git a/solutions/jenkins/Jenkinsfile b/solutions/jenkins/Jenkinsfile
--- a/solutions/jenkins/Jenkinsfile
+++ b/solutions/jenkins/Jenkinsfile
@@ -173,19 +173,45 @@ pipeline {
                     }
                 }
 
-                stage('Deploy worker microservice production k8s cluster') {
+                stage('build worker microservice deployment and service to k8s cluster') {
                     steps {
-                        echo 'Deploying the worker microservice'
-                        sh '''
-                            if [ -f "k8s/microdotnet.yaml" ]; then
+                    	echo 'Deploying the worker microservice to the k8s cluster'
+                        dir('solutions'){
+                            sh '''
+                            if [ -f "microservices/worker/microdotnet_deployment.yaml" ]; then
                                 export DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME
                                 envsubst < k8s/microdotnet.yaml | microk8s.kubectl apply -f -
                             else
                                 echo "No deployment file found"
                             fi
-                        '''
-                    }
-                }
+
+                                if [ -f "microservices/worker/microdotnet_deployment.yaml" ]; then
+                                    kubectl apply -f microservices/worker/microdotnet_deployment.yaml
+                                    if [ $? -eq 0 ]; then
+                                        echo "Deployment applied successfully"
+                                        if [ -f "microservices/worker/microdotnet_service.yaml" ]; then
+                                            kubectl apply -f microservices/worker/microdotnet_service.yaml
+                                            if [ $? -eq 0 ]; then
+                                                echo "Service applied successfully"
+                                            else
+                                                echo "Failed to apply service"
+                                                exit 1
+                                            fi
+                                        else
+                                            echo "No service file found"
+                                        fi
+                                    else
+                                        echo "Failed to apply deployment"
+                                        exit 1
+                                    fi
+                                else
+                                    echo "No deployment file found"
+                                fi			            
+			            '''                            
+		                }
+		            }
+		        }
+
             }
         }
 
